services:
#    neo_nasa.example:
#        class: Neo\NasaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  new_nasa.reponse_default:
    class: 'Neo\NasaBundle\Model\Response\DefaultResponse'
